image: mambaorg/micromamba

before_script:
  - echo "Installing pipeline dependencies"
  - mamba --version

  - mamba install -c bioconda -c conda-forge snakemake black

lint:
  script:
    - 'snakemake --version'
    - 'snakemake --lint --cores 1 --verbose'

black:
  script:
    - 'black . --check'
