before_script:
  - echo "Installing pipeline dependencies"
  - mamba --version
  - mamba install -c bioconda -c conda-forge snakemake==7.26.0 snakefmt
  - snakemake --version
  - black --version

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

lint-test:
  artifacts:
    paths: 
        - lint
  script:
    - snakemake --lint

smkformat:
  script:
    - echo "Running snakefmt"
    - snakefmt .

unit-test:
  script:
    - pytest .tests

run-test:
  artifacts:
    paths: 
        - smalltest
  script:
    - snakemake -p --use-conda --cores 1 --verbose
