image: mambaorg/micromamba

before_script:
  - echo "Installing pipeline dependencies"
  - conda update -n base -c defaults conda
  - conda install -c bioconda -c conda-forge snakemake black

lint:
  script:
    - 'snakemake --version'
    - 'snakemake --lint'

black:
  script:
    - 'black . --check'
