image: condaforge/mambaforge:23.3.1-1

before_script:
  - echo "Installing pipeline dependencies"
  - mamba --version
  - mamba config --set channel_priority strict
  - mamba install -c conda-forge -c bioconda python==3.12.3 snakemake==8.12.0 snakefmt==0.10.2 make
  - snakemake --version
  - black --version

# lint-test:
#   artifacts:
#     paths: 
#         - lint
#   script:
#     - snakemake --lint

smkformat:
  script:
    - echo "Running snakefmt"
    - snakefmt .

run-test:
  artifacts:
    paths: 
        - smalltest
  script:
    - snakemake -p --use-conda --cores 1 --verbose
