before_script:
  - echo "Installing pipeline dependencies"
  - conda --version
  - conda install -c bioconda -c conda-forge snakemake==6.12.3-0 black
  - snakemake --version
  - black --version

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

smklint:
  artifacts:
    paths: 
        - lint
  script:
    - snakemake --cores 1 --lint --verbose

black:
  script:
    - echo "Running python linter"
    - black . --check

test:
  script:
    - snakemake --version
    - snakemake -p --use-conda --cores 1 --verbose --dryrun
