image: mambaorg/micromamba:git-8e479d6-bookworm

before_script:
  - echo "Installing pipeline dependencies"
  - micromamba --version
  - micromamba config set channel_priority strict
  - micromamba install -c conda-forge -c bioconda python==3.12.3 snakemake==8.12.0 snakefmt==0.10.2
  - snakemake --version
  - black --version

# lint-test:
#   artifacts:
#     paths: 
#         - lint
#   script:
#     - snakemake --lint

smkformat:
  script:
    - echo "Running snakefmt"
    - snakefmt .

run-test:
  artifacts:
    paths: 
        - smalltest
  script:
    - snakemake -p --use-conda --cores 1 --verbose
