image: snakemake/snakemake

before_script:
  - echo "Installing CI/CD Depencencies"
  - mamba install -c bioconda -c conda-forge black

lint:
  script:
    - 'snakemake --version'
    - 'snakemake --lint'

black:
  script:
    - 'black . --check'
