before_script:
  - echo "Installing pipeline dependencies"
  - conda --version
  - conda install -c bioconda -c conda-forge snakemake==7.3.0 black
  - snakemake --version
  - black --version

# after_script:
#   - echo "After script section"
#   - echo "For example you might do some cleanup here"

smklint:
  artifacts:
    paths: 
        - lint
  script:
    - snakemake --lint

black:
  script:
    - echo "Running python linter"
    - black . --check

test:
  artifacts:
    paths: 
        - smalltest
  script:
    - snakemake --version
    - snakemake -p --use-conda --cores 1 --verbose
