image: miniconda3:4.4.10

before_script:
  - echo "Installing pipeline dependencies"
  - conda --version
  - conda install -c bioconda -c conda-forge snakemake
  - snakemake --version

test1:
  stage: test
  script:
    - snakemake --lint --cores 1 --configfile .test/config.yaml
