before_script:
  - source /home/gitlab-runner/miniforge3/etc/profile.d/conda.sh
  - conda activate defrabb-ci
  - echo "Pipeline tools (from pre-built defrabb-ci env)"
  - mamba --version
  - snakemake --version
  - snakefmt --version
  - black --version
  - pytest --version
  - apptainer --version

# lint-test:
#   artifacts:
#     paths:
#         - lint
#   script:
#     - snakemake --lint

smkformat:
  script:
    - echo "Running snakefmt"
    - snakefmt .

pytest:
  script:
    - echo "Running pytest"
    - pytest .tests

run-test:
  artifacts:
    paths:
        - smalltest
  script:
    - snakemake -p --use-conda --use-apptainer --cores 1 --verbose --config "_happy_threads=1"
