repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^envs/
      - id: check-added-large-files
        args: ["--maxkb=1024"]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/snakemake/snakefmt
    rev: v0.10.2
    hooks:
      - id: snakefmt
