$schema: "http://json-schema.org/draft-07/schema#"
description: whole genome assembly benchmark pipeline
required:
  - bench_id
  - bench_cmd
  # - bench_params
  - asm_id
  - ref
  - varcaller
  # - vc_params
  # - vcf_postprocessing
  # - bed_postprocessing
  - truth_var_id
  # - truth_regions
  - query_var_id
  - target_regions
  # - hpy_params
  - strat_version
  - strat_list
additionalProperties: false
properties:
  bench_id:
    description: |
      The ID for this analysis run. Every value in this column should be unique.
    type: string

  bench_cmd:
    description: |
      The benchmarking command to run. Must be either 'happy' or 'truvari'.
    type: string
    pattern: ^happy|truvari$

  bench_params:
    description: |
      Additional params to pass to the benchmarking command. See
      'target_regions' for how to control '--target-regions' (hap.py) and
      '--includebed' (truvari).
    type: string

  asm_id:
    description: the identifier of the assembly to use in resources.yml
    type: string

  ref:
    description: the identifier of the reference to use in resources.yml
    type: string
    pattern: ^GRCh3[7,8]$

  varcaller:
    description: the variant caller to use
    type: string
    # TODO for now only dipcall supported
    # pattern: ^dipcall|PAV$
    pattern: ^dipcall$

  vc_params:
    description: additional params to be passed to the varcaller
    type: string

  # TODO this is currently unused; what gets preprocessed when running this?
  vcf_postprocessing:
    description: steps to do prior to running the variant caller
    type: 'null'

  # TODO this is currently unused; what gets postprocessed when running this?
  bed_postprocessing:
    description: steps to do after running the variant caller
    type: 'null'

  truth_var_id:
    description: the id of the truth vcf file to use from resources.yml
    type: string

  # truth_regions:
  #   description: the id of the truth bed file to use from resources.yml
  #   type: string

  # TODO this doesn't seem necessary if each row = 1 combination
  query_var_id:
    description: a unique id given to the variant caller run
    type: string

  target_regions:
    description: |
      The target regions to input to happy. If 'true,' will be tell happy to use
      the bed file output by the variant caller. If a string, will be
      interpreted as a path to the bed file to use (relative to
      ./manual/target_regions). If 'false,' happy will run in untargetted mode.
    anyOf:
      - type: boolean
      - type: string

  strat_version:
    description: the versions of stratifications to use
    type: string

  strat_list:
    description: the .tsv within the stratification tarball/download list to use
    type: string
    

