# v4.1 gabp pipeline

##############################################
## User Defined paramaters
##############################################

############# Assembly Paths ################
# URL to the maternal/paternal assemblies
assemblies:
  maternal: https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/6AA58BE2-3710-4B27-AB6A-BEC23DBA14A2--RU-HG002-cleaned/HG002/assemblies/bakeoff/ru_scaffolded/HG002.mat.gap_filled_scaff.cleaned.fa.gz
  paternal: https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/6AA58BE2-3710-4B27-AB6A-BEC23DBA14A2--RU-HG002-cleaned/HG002/assemblies/bakeoff/ru_scaffolded/HG002.pat.gap_filled_scaff.cleaned.fa.gz

# TODO this is a hack so I don't need to rewrite all the prefix logic now,
# change this to make more sense eventually (it supposed to be a list)
ASM_prefix:
  - whole-assembly

############# Gender #######################
# if sample for Dipcall is male
# Enter "true" or "false"
male: true

############# Dipcall Config #######################
# number of threads for Dipcall (integer)
dipcall_threads: 1

# zdrop param for minimap2 in dipcall
dipcall_zdrop: "20000,10000"

############# Reference  ###################
# Reference to use for variant calling with
# Dipcall.
# Enter "GRCh38" or "GRCh37"
reference: "GRCh38"

# ############# Benchmark  ###################
# # version number of benchmark being used, this will be used in hap.py output filename prefix
# # e.g., v4.1
benchmark_version: "4.2.1"

# TODO use a base FTP directory and add things onto it depending on which benchmark files we want
# # enter ftp path to benchmark vcf.gz to be used, e.g.,
benchmark_vcfgz: "ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz"

# # enter ftp path to corresponding vcf.gz index file, e.g.,
benchmark_vcfgz_tbi: "ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark.vcf.gz.tbi"

# # enter ftp path to benchmark bed to be used, e.g.,
benchmark_bed: "ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/AshkenazimTrio/HG002_NA24385_son/latest/GRCh38/HG002_GRCh38_1_22_v4.2.1_benchmark_noinconsistent.bed"

##############################################

##############################################
## Tool resources -- DO NOT CHANGE
##############################################

## TODO probably a better, less brittle way to represent this (another tsv file?)

par_bed_root: "data/par_bed"

tool_data:
  GRCh37:
    ref_url: "ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/phase2_reference_assembly_sequence/hs37d5.fa.gz"
    par_bed: "hs37d5.PAR.bed"
    strat_id: "GRCh37-stratifications-v2.0"
    strat_url: "ftp://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v2.0/GRCh37/"
    strat_tsv: "v2.0-GRCh37-stratifications.tsv"
  GRCh38:
    ref_url: "ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
    par_bed: "hs38.PAR.bed"
    strat_id: "GRCh38-stratifications-v2.0"
    strat_url: "ftp://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/release/genome-stratifications/v2.0/GRCh38/"
    strat_tsv: "v2.0-GRCh38-stratifications.tsv"
